### ISSUE TITLE
unable to set parameters

### ISSUE THREAD

**Issue by kossumov** [bydottck13/aws_mqtt_bridge#1]
Hey guys,

When I launch aws_mqtt_bridge I get the following error:

**load_parameters: unable to set parameters (last param was [/aws_mqtt_node/bridge=[{'topic_from': 'aws_to_device/chatter', 'topic_to': 'chatter', 'msg_type': 'std_msgs.msg:String'}, {'topic_from': 'aws_to_device/turtlesim', 'topic_to': '/turtle1/cmd_vel', 'msg_type': 'geometry_msgs.msg:Twist'}]]): cannot marshal None unless allow_none is enabled**

Looks like for some reason it cannot load _aws-to-ros_ and _ros-to-aws_ topics' parameters

What might be the reason?
Thanks :)

**Comment by kossumov** [comment]
ok, I got it.
did not remove curly brackets inside _demo_params.yaml_

**Comment by bydottck13** [comment]
@kossumov Cool, did you eventually fix it? I'm happy to answer if you have other questions.

**Comment by kossumov** [comment]
yep, I fixed it. Thanks
