### ISSUE TITLE
Cannot connect to AWS IoT...

### ISSUE THREAD

**Issue by kossumov** [bydottck13/aws_mqtt_bridge#2]
I did everything according to instructions inside README.md.
However, when I launch aws_mqtt_bridge (_roslaunch aws_mqtt_bridge demo.launch_) the following line fails (app.py line 55)
`raise IOError("Cannot connect to AWS IoT...")`

What might be the problem?
Thanks

log file (aws_mqtt_node-2.log):
`[rospy.client][INFO] 2018-09-22 17:30:05,457: init_node, name[/aws_mqtt_node], pid[11612]
[xmlrpc][INFO] 2018-09-22 17:30:05,457: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-09-22 17:30:05,457: Started XML-RPC server [http://azat-GL502VSK:34745/]
[rospy.init][INFO] 2018-09-22 17:30:05,458: ROS Slave URI: [http://azat-GL502VSK:34745/]
[rospy.impl.masterslave][INFO] 2018-09-22 17:30:05,458: _ready: http://azat-GL502VSK:34745/
[rospy.registration][INFO] 2018-09-22 17:30:05,458: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-09-22 17:30:05,458: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-09-22 17:30:05,558: registered with master
[rospy.rosout][INFO] 2018-09-22 17:30:05,559: initializing /rosout core topic
[rospy.rosout][INFO] 2018-09-22 17:30:05,565: connected to core topic /rosout
[rospy.simtime][INFO] 2018-09-22 17:30:05,567: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][DEBUG] 2018-09-22 17:30:05,568: init_node, name[/aws_mqtt_node], pid[11612]
[rosout][DEBUG] 2018-09-22 17:30:05,569: binding to 0.0.0.0 0
[rosout][DEBUG] 2018-09-22 17:30:05,569: bound to 0.0.0.0 34683
[rosout][DEBUG] 2018-09-22 17:30:05,570: ... service URL is rosrpc://azat-GL502VSK:34683
[rosout][DEBUG] 2018-09-22 17:30:05,570: [/aws_mqtt_node/get_loggers]: new Service instance
[rosout][DEBUG] 2018-09-22 17:30:05,574: ... service URL is rosrpc://azat-GL502VSK:34683
[rosout][DEBUG] 2018-09-22 17:30:05,574: [/aws_mqtt_node/set_logger_level]: new Service instance
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,582: MqttCore initialized
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,582: Client id: x370rover
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,582: Protocol version: MQTTv3.1.1
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,582: Authentication type: TLSv1.2 certificate based Mutual Auth.
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,583: Configuring endpoint...
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,583: Configuring certificates...
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,583: Configuring reconnect back off timing...
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,583: Base quiet time: 1.000000 sec
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,583: Max quiet time: 32.000000 sec
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,583: Stable connection time: 20.000000 sec
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,584: Configuring offline requests queueing: max queue size: -1
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,584: Configuring offline requests queue draining interval: 0.500000 sec
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,584: Configuring connect/disconnect time out: 10.000000 sec
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,585: Configuring MQTT operation time out: 5.000000 sec
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,585: Performing sync connect...
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,585: Performing async connect...
[AWSIoTPythonSDK.core.protocol.mqtt_core][INFO] 2018-09-22 17:30:05,585: Keep-alive: 600.000000 sec
[rospy.internal][INFO] 2018-09-22 17:30:05,864: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2018-09-22 17:30:08,390: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-09-22 17:30:08,396: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2018-09-22 17:30:08,396: atexit`

**Comment by kossumov** [comment]
When I print the exception I get:
[ERROR] [1537633357.353978]: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by bydottck13** [comment]
Did you change the path of your certificates in demo_params.yaml? And, by the way, you should setup the MQTT server in AWS as well. You can refer this(https://docs.aws.amazon.com/iot/latest/developerguide/iot-console-signin.html) to follow the instructions. Additionally, the step 3 "Create and Activate a Device Certificate" will teach you how to generate certificates, and you should download them and put in the directory. Finally, modify the parameters in demo_params.yaml.

**Comment by kossumov** [comment]
I've already done all of that

**Comment by kossumov** [comment]
I figured out what was the problem.
Looks like from my location for some reason I cannot use Amazon Trust Services Endpoints (root ca).
Replaced it with VeriSign Endpoints (legacy).
Works fine ;)
